### ISSUE TITLE
[BUG] Module not found

### ISSUE THREAD

**Issue by ddavies1972** [VainlyStrain/Vailyn#18]
**Category**
| Program Crash |

**Describe the bug**
The program gives the error:
└─# python3.8 Vailyn
Traceback (most recent call last):
  File "Vailyn", line 40, in <module>
    from PyQt5.QtCore import Qt
ModuleNotFoundError: No module named 'PyQt5.sip'

I have installed all required modules, yet get above error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Arguments used '...'
2. Selected payloads '....'
3. See error '....'

**Expected behaviour**
The program to run.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kali rolling (fully updated)
 - Program Version latest
 - Python Version 3.8

**Additional context**

**Comment by VainlyStrain** [comment]
Hi!

This is very strange, and I cannot reproduce it on my end. However, this seems like a broken installation of PyQt5, since sip is a dependency of that package, and should have been installed together with PyQt5. How did you install PyQt5 (pip or apt)? What does the following command say?:

```
$ pip install --upgrade PyQt5  # or pip3, if you have python2 as default interpreter
```

**Comment by VainlyStrain** [comment]
According to [this question](https://stackoverflow.com/questions/55087069/no-module-named-pyqt5-sip), this seems to be a bug with PyQt5 5.15. Since Kali-rolling seems to use this version, temporarily downgrading to PyQt5 5.14 should resolve the issue.

Unfortunately, this error is caused inside PyQt itself, so I cannot do anything about it in my code. If you cannot downgrade PyQt5, another solution would be to delete everything related to the GUI in the main `Vailyn` file, and to only use the CLI.

Greetings!

**Comment by ddavies1972** [comment]
Downgraded and works ok now, Thanks!
