### ISSUE TITLE
[Observation] Pre-run loading takes a long time

### ISSUE THREAD

**Issue by juushya** [VainlyStrain/Vailyn#3]
Greetings!

I started the first run about 25 minutes back. The % loading is at 13%. This is a query attack run (-a 1) with a very short file & directory list (<10 entries).

1. Is this expected behavior? Or it is only a first-run behavior?
2. What parameters does this loading depend on? Is there a way to speed this up?

![image](https://user-images.githubusercontent.com/4639200/89132330-f859c280-d530-11ea-8222-1051c171931e.png)

Thanks.

**Comment by VainlyStrain** [comment]
This does sound suspicious. May I please have some more information on

* the exact dictionary sizes (number of lines)
* the dictionary structure for both

Also, are you currently in Phase 1 or 2? Phase 1 is not affected by the dictionaries and has (without external factors) constant runtime (for same depth), while the second phase grows with dict sizes).

More factors that influence speed are hardware specs (both user and server) & network performance. So, I'd suggest (if you can & want) to compare the performance to a similar tool using same options to see if it is an issue with it, or if there is an external factor at play. Because most tools only do phase 2, you can create a payloads.cache and nullbytes.cache file to skip phase 1 for better comparison.

Greetings

Edit: Tested it on an external server (with dict sizes 35 and 10, default depth), and it took around 5 minutes in total, so the issue (seems) to be related to an external factor.

For 2): this percentage marks the progress in the phase 1 of the attack. So, it is actually fully loaded and is currently scanning the server. Thus, it depends on:

* the size of the payload list, multiplied with the size of the nullbyte list +1
* the attack depth set (-d I J  I for Phase 1)

You can reduce the time by taking with `-i FIL` a file you know exists on the server. For instance, you can take the index.php file, and set the depth very low.

**Comment by juushya** [comment]
I believe this is Phase 1 run. I am using the same wordlist as both file & directory list. 
Testing on Kali VM - ~8 gigs RAM, single CPU. This tool looks interesting, so decided to play with it :)

```
# cat /tmp/a 
.htpasswd
.passwd
chpasswd
htpasswd
master.passwd
passwd
etc
```
![image](https://user-images.githubusercontent.com/4639200/89132811-9602c100-d534-11ea-8488-82e83eea67f0.png)

**Comment by VainlyStrain** [comment]
If you are running it on a single CPU, then it will indeed take quite some time, since you won't benefit from the multiprocessing abilities. So, I'd suggest to try and shorten Phase 1 as much as possible (using above trick with the known-file-low-depth).

Also, for Phase 2, you will need to specify different dictionaries.

The first one must only contain file names, and the second one only directory names. Else, you will have requests like this

../../../index.php/etc/secret.txt/html/

which won't work.

Greetings!

Oh, and I also just noticed a directory dictionary handling error (it would not check if lines end with /. Going to fix this soon.

**Comment by juushya** [comment]
Attempting another run with 2 different files - one for directory (content: /etc/) and second for file (passwd):
`python3 Vailyn -v 'http://<domain>/news.php' -p file -a 1 -l a b -d 7 7`

Would be great do have a verbose option to see / verify payloads & requests going out, and some examples on usage :)

Cheers~

Edit: will allocate multi CPUs to VM as well

**Comment by VainlyStrain** [comment]
Ok, will expand the `--debug` argument (doing exactly what you requested) to Phase 1 :) also, will add some examples to README. Thank you for the feedback :+1:

**Comment by VainlyStrain** [comment]
closing, since it does seem to be related to external factors. If the time does not decrease at all with the multi-CPU VM, please contact me, and the issue will be reopened.
